In [1]:
import torch
import numpy as np
from torch.nn import functional as F
import time
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [2]:
%%time
start_time=time.time()
zeros=torch.zeros(1,1)
end_time=time.time()
elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")

0.01105428
CPU times: total: 15.6 ms
Wall time: 14.8 ms


In [3]:
torch_rand1=torch.rand(100,100,100,100).to(device)
torch_rand2=torch.rand(100,100,100,100).to(device)
np_rand1=torch.rand(100,100,100,100)
np_rand2=torch.rand(100,100,100,100)

start_time=time.time()
rand=(torch_rand1 @ torch_rand2)
end_time=time.time()
elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")

start_time=time.time()
rand=np.multiply(np_rand1,np_rand2)
end_time=time.time()
elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")


0.16648126
0.11353707


C:\Users\bheem\AppData\Local\Temp\ipykernel_5676\2125396169.py:13: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand=np.multiply(np_rand1,np_rand2)


In [4]:
probabilities=torch.tensor([0.1,0.9])
samples=torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [5]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out=torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out=torch.triu(torch.ones(5,5))
out


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [11]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([4,5,6])
t3=torch.tensor([7,8,9])

stacked_t=torch.stack([t1,t2,t3])
stacked_t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ -9.6912, -12.8576,  -4.7464], grad_fn=<SqueezeBackward4>)


In [13]:
import torch.nn.functional as F
t1=torch.tensor([1.0,2.0,3.0])
softmax_output=F.softmax(t1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(a@b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [15]:
x=torch.tensor([-0.05],dtype=torch.float32)
y=F.sigmoid(x)
print(y)

tensor([0.4875])
